#ifndef _IO_H_
#define _IO_H_

#include "stm8s.h"

typedef enum
{
	LOW,
	HIGH,
	REVERSE
} GPIO_State_TypeDef;

typedef struct
{
	GPIO_TypeDef *port;
	GPIO_Pin_TypeDef pin;
	GPIO_Mode_TypeDef mode;
	GPIO_State_TypeDef state;
} GPIO_Line_TypeDef;

#define IO_TABLE\
	X_IO(io_DISPLAY_SEG_A, GPIOD, GPIO_PIN_1, GPIO_MODE_OUT_PP_LOW_SLOW, LOW) \
	X_IO(io_DISPLAY_SEG_B, GPIOA, GPIO_PIN_3, GPIO_MODE_OUT_PP_LOW_SLOW, LOW) \
	X_IO(io_DISPLAY_SEG_C, GPIOC, GPIO_PIN_3, GPIO_MODE_OUT_PP_LOW_SLOW, LOW) \
	X_IO(io_DISPLAY_SEG_D, GPIOC, GPIO_PIN_6, GPIO_MODE_OUT_PP_LOW_SLOW, LOW) \
	X_IO(io_DISPLAY_SEG_E, GPIOC, GPIO_PIN_7, GPIO_MODE_OUT_PP_LOW_SLOW, LOW) \
	X_IO(io_DISPLAY_SEG_F, GPIOC, GPIO_PIN_4, GPIO_MODE_OUT_PP_LOW_SLOW, LOW) \
	X_IO(io_DISPLAY_SEG_G, GPIOA, GPIO_PIN_2, GPIO_MODE_OUT_PP_LOW_SLOW, LOW) \
	X_IO(io_DISPLAY_SEG_DP, GPIOC, GPIO_PIN_5, GPIO_MODE_OUT_PP_LOW_SLOW, LOW) \
	X_IO(io_DISPLAY_VOLTMETER_DIGIT_1, GPIOD, GPIO_PIN_5, GPIO_MODE_OUT_PP_LOW_SLOW, HIGH) \
	X_IO(io_DISPLAY_VOLTMETER_DIGIT_2, GPIOD, GPIO_PIN_6, GPIO_MODE_OUT_PP_LOW_SLOW, HIGH) \
	X_IO(io_DISPLAY_VOLTMETER_DIGIT_3, GPIOD, GPIO_PIN_4, GPIO_MODE_OUT_PP_LOW_SLOW, HIGH) \
	X_IO(io_DISPLAY_AMPERMETER_DIGIT_1, GPIOA, GPIO_PIN_1, GPIO_MODE_OUT_PP_LOW_SLOW, HIGH) \
	X_IO(io_DISPLAY_AMPERMETER_DIGIT_2, GPIOB, GPIO_PIN_4, GPIO_MODE_OUT_PP_LOW_SLOW, HIGH) \
	X_IO(io_DISPLAY_AMPERMETER_DIGIT_3, GPIOB, GPIO_PIN_5, GPIO_MODE_OUT_PP_LOW_SLOW, HIGH) \
	X_IO(io_VOLTMETER_ADC, GPIOD, GPIO_PIN_3, GPIO_MODE_IN_FL_NO_IT, LOW) \
	X_IO(io_AMPERMETER_ADC, GPIOD, GPIO_PIN_2, GPIO_MODE_IN_FL_NO_IT, LOW) \
	
typedef enum
{
	#define X_IO(a,b,c,d,e) a,
	IO_TABLE
	#undef X_IO
	NUM_IO //count
} IOLine_TypeDef;

void IO_Init(void);
void IO_ConfigLine(IOLine_TypeDef line, GPIO_Mode_TypeDef mode);
void IO_SetLine(IOLine_TypeDef line, GPIO_State_TypeDef state);

#endif
